Stats
RNAer/micronota pull request #4
Opened 2017-05-27 00:49 UTC by qiyunzhu

Hi @RNAer I have written the first function `summarize`. I am not sure how to use the scikit-bio `IntervalMetadata` object since I can't find the documents, nor do I think it has `length` or `nucl_freq` properties. So I left it out. I added two test datasets: 1) the genome of _Candidatus_ Carsonella ruddii PV, which is the smallest in the world, and 2) the genome of _Mycoplasma genitalium_ G37, which is among the smallest in the world, and is fragmental.

2017-05-27 01:01 UTC, RNAer commented
dont understand why you can't find the documentation: http://scikit-bio.org/docs/latest/generated/skbio.metadata.IntervalMetadata.html?highlight=intervalmetadata...

could you do it like done here: https://github.com/RNAer/micronota/blob/snakemake/micronota/workflow.py#L298?

you can resolve the conflicts with https://help.github.com/articles/resolving-a-merge-conflict-on-github/

2017-05-27 02:10 UTC, qiyunzhu commented
@RNAer Thanks for inspiration! Will explore soon.

2017-05-27 18:47 UTC, qiyunzhu commented
Hi @RNAer I think that a `IntervalMetadata` object does not have length or nucleotide frequency information. Therefore, your original design, which lets the parameter of `summarize` to be either `Sequence` or `IntervalMetadata` not possible. So I kep only `Sequence`.

2017-06-08 00:40 UTC, RNAer requested changes
looks good overall. a couple of comments. thanks!

2017-06-08 00:40 UTC, RNAer commented on micronota/summarize.py
> +    return len([x for x in obj.interval_metadata._intervals
use the public `interval_metadata.query` instead of the private attr `._intervals`, which may be subject to changes in future

2017-06-08 00:40 UTC, RNAer commented on micronota/summarize.py
> +    return tuple(stats)
it is probably fine to just return list

2017-06-08 22:42 UTC, qiyunzhu commented
Hello Zech I have taken care of your comments. @RNAer

2017-06-08 22:42 UTC, qiyunzhu commented on micronota/summarize.py
> +    return len([x for x in obj.interval_metadata._intervals
Done.

2017-06-08 22:42 UTC, qiyunzhu commented on micronota/summarize.py
> +    return tuple(stats)
Done.

2017-07-21 00:55 UTC, RNAer commented
@qiyunzhu , looks good! The AA*.gz are not used. could you remove them? then I'll merge. thanks!

2017-07-21 19:33 UTC, qiyunzhu commented
@RNAer Got it! Removed.

2017-07-21 19:53 UTC, RNAer commented
Thanks!

2017-07-21 19:53 UTC, merged